{-# LANGUAGE PatternSynonyms #-}
module Country.Identifier where

-- This module is autogenerated. Do not edit it by hand.

import Country.Unsafe (Country(..))

-- | Afghanistan
afghanistan :: Country
afghanistan = Country 4

pattern Afghanistan :: Country
pattern Afghanistan = Country 4

-- | Aaland Islands; Aland Islands; Åland; Åland Islands
ålandIslands :: Country
ålandIslands = Country 248

pattern ÅlandIslands :: Country
pattern ÅlandIslands = Country 248

-- | Albania; Arbanon; Republic of Albania; Republika e Shqipërisë
albania :: Country
albania = Country 8

pattern Albania :: Country
pattern Albania = Country 8

-- | Algeria; Algérie; Dzayer; People's Democratic Republic of Algeria; al Jumhuriyya al Jazaa'iriyya ad-Dīmuqrāţiyya ash Sha'biyya; al-Jazā'ir; الجزائر; ⴷⵣⴰⵢⴻⵔ
algeria :: Country
algeria = Country 12

pattern Algeria :: Country
pattern Algeria = Country 12

-- | American Samoa
americanSamoa :: Country
americanSamoa = Country 16

pattern AmericanSamoa :: Country
pattern AmericanSamoa = Country 16

-- | Andorra
andorra :: Country
andorra = Country 20

pattern Andorra :: Country
pattern Andorra = Country 20

-- | Angola
angola :: Country
angola = Country 24

pattern Angola :: Country
pattern Angola = Country 24

-- | Anguilla
anguilla :: Country
anguilla = Country 660

pattern Anguilla :: Country
pattern Anguilla = Country 660

-- | Antarctica
antarctica :: Country
antarctica = Country 10

pattern Antarctica :: Country
pattern Antarctica = Country 10

-- | Antigua and Barbuda
antiguaAndBarbuda :: Country
antiguaAndBarbuda = Country 28

pattern AntiguaAndBarbuda :: Country
pattern AntiguaAndBarbuda = Country 28

-- | Argentina; Argentine Confederation; Argentine Nation; Argentine Republic; La Argentina; The Argentine; United Provinces of the Río de la Plata; la Argentina; the Argentine
argentina :: Country
argentina = Country 32

pattern Argentina :: Country
pattern Argentina = Country 32

-- | Armenia
armenia :: Country
armenia = Country 51

pattern Armenia :: Country
pattern Armenia = Country 51

-- | Aruba
aruba :: Country
aruba = Country 533

pattern Aruba :: Country
pattern Aruba = Country 533

-- | Australia; Commonwealth of Australia; New Holland
australia :: Country
australia = Country 36

pattern Australia :: Country
pattern Australia = Country 36

-- | Austria; Republic of Austria; Republik Österreich; Österreich
austria :: Country
austria = Country 40

pattern Austria :: Country
pattern Austria = Country 40

-- | Azerbaijan
azerbaijan :: Country
azerbaijan = Country 31

pattern Azerbaijan :: Country
pattern Azerbaijan = Country 31

-- | Bahamas
bahamas :: Country
bahamas = Country 44

pattern Bahamas :: Country
pattern Bahamas = Country 44

-- | Bahrain
bahrain :: Country
bahrain = Country 48

pattern Bahrain :: Country
pattern Bahrain = Country 48

-- | Bangladesh
bangladesh :: Country
bangladesh = Country 50

pattern Bangladesh :: Country
pattern Bangladesh = Country 50

-- | Barbados
barbados :: Country
barbados = Country 52

pattern Barbados :: Country
pattern Barbados = Country 52

-- | Belarus
belarus :: Country
belarus = Country 112

pattern Belarus :: Country
pattern Belarus = Country 112

-- | Belgium
belgium :: Country
belgium = Country 56

pattern Belgium :: Country
pattern Belgium = Country 56

-- | Belize
belize :: Country
belize = Country 84

pattern Belize :: Country
pattern Belize = Country 84

-- | Benin
benin :: Country
benin = Country 204

pattern Benin :: Country
pattern Benin = Country 204

-- | Bermuda
bermuda :: Country
bermuda = Country 60

pattern Bermuda :: Country
pattern Bermuda = Country 60

-- | Bhutan
bhutan :: Country
bhutan = Country 64

pattern Bhutan :: Country
pattern Bhutan = Country 64

-- | Bolivia; Bolivia (Plurinational State of); Plurinational State of Bolivia
boliviaPlurinationalStateOf :: Country
boliviaPlurinationalStateOf = Country 68

pattern BoliviaPlurinationalStateOf :: Country
pattern BoliviaPlurinationalStateOf = Country 68

-- | Bonaire, Sint Eustatius and Saba; Bonaire, Sint Eustatius, and Saba
bonaireSintEustatiusAndSaba :: Country
bonaireSintEustatiusAndSaba = Country 535

pattern BonaireSintEustatiusAndSaba :: Country
pattern BonaireSintEustatiusAndSaba = Country 535

-- | Bosnia and Herzegovina
bosniaAndHerzegovina :: Country
bosniaAndHerzegovina = Country 70

pattern BosniaAndHerzegovina :: Country
pattern BosniaAndHerzegovina = Country 70

-- | Botswana
botswana :: Country
botswana = Country 72

pattern Botswana :: Country
pattern Botswana = Country 72

-- | Bouvet Island
bouvetIsland :: Country
bouvetIsland = Country 74

pattern BouvetIsland :: Country
pattern BouvetIsland = Country 74

-- | Brazil; Empire of Brazil; Federative Republic of Brazil; Ilha de Vera Cruz; Pindorama; República Federativa do Brasil; Terra de Santa Cruz; Terra di Papaga; United States of Brazil
brazil :: Country
brazil = Country 76

pattern Brazil :: Country
pattern Brazil = Country 76

-- | British Indian Ocean Territory
britishIndianOceanTerritory :: Country
britishIndianOceanTerritory = Country 86

pattern BritishIndianOceanTerritory :: Country
pattern BritishIndianOceanTerritory = Country 86

-- | Brunei; Brunei Darussalam
bruneiDarussalam :: Country
bruneiDarussalam = Country 96

pattern BruneiDarussalam :: Country
pattern BruneiDarussalam = Country 96

-- | Bulgaria
bulgaria :: Country
bulgaria = Country 100

pattern Bulgaria :: Country
pattern Bulgaria = Country 100

-- | Burkina Faso
burkinaFaso :: Country
burkinaFaso = Country 854

pattern BurkinaFaso :: Country
pattern BurkinaFaso = Country 854

-- | Burundi
burundi :: Country
burundi = Country 108

pattern Burundi :: Country
pattern Burundi = Country 108

-- | Cambodia; Democratic Kampuchea; Kingdom of Cambodia; Royaume du Cambodge
cambodia :: Country
cambodia = Country 116

pattern Cambodia :: Country
pattern Cambodia = Country 116

-- | Cameroon
cameroon :: Country
cameroon = Country 120

pattern Cameroon :: Country
pattern Cameroon = Country 120

-- | Canada
canada :: Country
canada = Country 124

pattern Canada :: Country
pattern Canada = Country 124

-- | Cabo Verde; Cape Verde
caboVerde :: Country
caboVerde = Country 132

pattern CaboVerde :: Country
pattern CaboVerde = Country 132

-- | Cayman Islands
caymanIslands :: Country
caymanIslands = Country 136

pattern CaymanIslands :: Country
pattern CaymanIslands = Country 136

-- | Central African Republic
centralAfricanRepublic :: Country
centralAfricanRepublic = Country 140

pattern CentralAfricanRepublic :: Country
pattern CentralAfricanRepublic = Country 140

-- | Chad
chad :: Country
chad = Country 148

pattern Chad :: Country
pattern Chad = Country 148

-- | Capitania general de Chile; Chile; Chili; Chilli; Republic of Chile; Reyno de Chile
chile :: Country
chile = Country 152

pattern Chile :: Country
pattern Chile = Country 152

-- | China
china :: Country
china = Country 156

pattern China :: Country
pattern China = Country 156

-- | Christmas Island
christmasIsland :: Country
christmasIsland = Country 162

pattern ChristmasIsland :: Country
pattern ChristmasIsland = Country 162

-- | Cocos (Keeling) Islands; Cocos Islands; Cocos [Keeling] Islands; Keeling Islands
cocosKeelingIslands :: Country
cocosKeelingIslands = Country 166

pattern CocosKeelingIslands :: Country
pattern CocosKeelingIslands = Country 166

-- | Colombia
colombia :: Country
colombia = Country 170

pattern Colombia :: Country
pattern Colombia = Country 170

-- | Comoros
comoros :: Country
comoros = Country 174

pattern Comoros :: Country
pattern Comoros = Country 174

-- | Congo; DR Congo; Democratic Republic of the Congo; Republic of the Congo
congo :: Country
congo = Country 178

pattern Congo :: Country
pattern Congo = Country 178

-- | Congo (Democratic Republic of the)
congoDemocraticRepublicOfThe :: Country
congoDemocraticRepublicOfThe = Country 180

pattern CongoDemocraticRepublicOfThe :: Country
pattern CongoDemocraticRepublicOfThe = Country 180

-- | Cook Islands
cookIslands :: Country
cookIslands = Country 184

pattern CookIslands :: Country
pattern CookIslands = Country 184

-- | Costa Rica
costaRica :: Country
costaRica = Country 188

pattern CostaRica :: Country
pattern CostaRica = Country 188

-- | Côte d'Ivoire; Ivory Coast; Republic of Côte d'Ivoire
côteDivoire :: Country
côteDivoire = Country 384

pattern CôteDivoire :: Country
pattern CôteDivoire = Country 384

-- | Croatia
croatia :: Country
croatia = Country 191

pattern Croatia :: Country
pattern Croatia = Country 191

-- | Cuba
cuba :: Country
cuba = Country 192

pattern Cuba :: Country
pattern Cuba = Country 192

-- | Curaçao
curaçao :: Country
curaçao = Country 531

pattern Curaçao :: Country
pattern Curaçao = Country 531

-- | Cyprus
cyprus :: Country
cyprus = Country 196

pattern Cyprus :: Country
pattern Cyprus = Country 196

-- | Czech Republic; Czechia; Česko; Česká republika
czechRepublic :: Country
czechRepublic = Country 203

pattern CzechRepublic :: Country
pattern CzechRepublic = Country 203

-- | Danmark; Denmark; Kingdom of Denmark; Kongeriget Danmark
denmark :: Country
denmark = Country 208

pattern Denmark :: Country
pattern Denmark = Country 208

-- | Côte française des Somalis, Territoire d'Obock; Djibouti; French Somaliland; French Territory of the Afars and the Issas; Obock Territory; Republic of Djibouti; République de Djibouti; Territoire français des Afars et des Issas
djibouti :: Country
djibouti = Country 262

pattern Djibouti :: Country
pattern Djibouti = Country 262

-- | Dominica
dominica :: Country
dominica = Country 212

pattern Dominica :: Country
pattern Dominica = Country 212

-- | Dominican Republic
dominicanRepublic :: Country
dominicanRepublic = Country 214

pattern DominicanRepublic :: Country
pattern DominicanRepublic = Country 214

-- | Ecuador
ecuador :: Country
ecuador = Country 218

pattern Ecuador :: Country
pattern Ecuador = Country 218

-- | Aegyptus; Egypt; Meṣr
egypt :: Country
egypt = Country 818

pattern Egypt :: Country
pattern Egypt = Country 818

-- | El Salvador
elSalvador :: Country
elSalvador = Country 222

pattern ElSalvador :: Country
pattern ElSalvador = Country 222

-- | Equatorial Guinea
equatorialGuinea :: Country
equatorialGuinea = Country 226

pattern EquatorialGuinea :: Country
pattern EquatorialGuinea = Country 226

-- | Eritrea
eritrea :: Country
eritrea = Country 232

pattern Eritrea :: Country
pattern Eritrea = Country 232

-- | Estonia
estonia :: Country
estonia = Country 233

pattern Estonia :: Country
pattern Estonia = Country 233

-- | Ethiopia
ethiopia :: Country
ethiopia = Country 231

pattern Ethiopia :: Country
pattern Ethiopia = Country 231

-- | Falkland Islands; Falkland Islands (Malvinas); Falkland Islands [Malvinas]
falklandIslandsMalvinas :: Country
falklandIslandsMalvinas = Country 238

pattern FalklandIslandsMalvinas :: Country
pattern FalklandIslandsMalvinas = Country 238

-- | Faroe Islands
faroeIslands :: Country
faroeIslands = Country 234

pattern FaroeIslands :: Country
pattern FaroeIslands = Country 234

-- | Fiji
fiji :: Country
fiji = Country 242

pattern Fiji :: Country
pattern Fiji = Country 242

-- | Finland
finland :: Country
finland = Country 246

pattern Finland :: Country
pattern Finland = Country 246

-- | Farança; France; French Republic; La France; République Française
france :: Country
france = Country 250

pattern France :: Country
pattern France = Country 250

-- | French Guiana
frenchGuiana :: Country
frenchGuiana = Country 254

pattern FrenchGuiana :: Country
pattern FrenchGuiana = Country 254

-- | French Polynesia
frenchPolynesia :: Country
frenchPolynesia = Country 258

pattern FrenchPolynesia :: Country
pattern FrenchPolynesia = Country 258

-- | French Southern Territories
frenchSouthernTerritories :: Country
frenchSouthernTerritories = Country 260

pattern FrenchSouthernTerritories :: Country
pattern FrenchSouthernTerritories = Country 260

-- | Gabon
gabon :: Country
gabon = Country 266

pattern Gabon :: Country
pattern Gabon = Country 266

-- | Gambia
gambia :: Country
gambia = Country 270

pattern Gambia :: Country
pattern Gambia = Country 270

-- | Georgia
georgia :: Country
georgia = Country 268

pattern Georgia :: Country
pattern Georgia = Country 268

-- | BRD; Bundesrepublik Deutschland; Deutschland; FRG; Federal Republic of Germany; Germany
germany :: Country
germany = Country 276

pattern Germany :: Country
pattern Germany = Country 276

-- | Ghana
ghana :: Country
ghana = Country 288

pattern Ghana :: Country
pattern Ghana = Country 288

-- | Gibraltar
gibraltar :: Country
gibraltar = Country 292

pattern Gibraltar :: Country
pattern Gibraltar = Country 292

-- | Greece
greece :: Country
greece = Country 300

pattern Greece :: Country
pattern Greece = Country 300

-- | Greenland
greenland :: Country
greenland = Country 304

pattern Greenland :: Country
pattern Greenland = Country 304

-- | Grenada
grenada :: Country
grenada = Country 308

pattern Grenada :: Country
pattern Grenada = Country 308

-- | Guadeloupe
guadeloupe :: Country
guadeloupe = Country 312

pattern Guadeloupe :: Country
pattern Guadeloupe = Country 312

-- | Guam
guam :: Country
guam = Country 316

pattern Guam :: Country
pattern Guam = Country 316

-- | Guatemala
guatemala :: Country
guatemala = Country 320

pattern Guatemala :: Country
pattern Guatemala = Country 320

-- | Guernsey
guernsey :: Country
guernsey = Country 831

pattern Guernsey :: Country
pattern Guernsey = Country 831

-- | Guinea
guinea :: Country
guinea = Country 324

pattern Guinea :: Country
pattern Guinea = Country 324

-- | Guinea-Bissau
guineabissau :: Country
guineabissau = Country 624

pattern Guineabissau :: Country
pattern Guineabissau = Country 624

-- | Guyana
guyana :: Country
guyana = Country 328

pattern Guyana :: Country
pattern Guyana = Country 328

-- | Haiti
haiti :: Country
haiti = Country 332

pattern Haiti :: Country
pattern Haiti = Country 332

-- | Heard Island and McDonald Islands; Heard and McDonald Islands
heardIslandAndMcdonaldIslands :: Country
heardIslandAndMcdonaldIslands = Country 334

pattern HeardIslandAndMcdonaldIslands :: Country
pattern HeardIslandAndMcdonaldIslands = Country 334

-- | Holy See; Vatican; Vatican City
holySee :: Country
holySee = Country 336

pattern HolySee :: Country
pattern HolySee = Country 336

-- | Honduras
honduras :: Country
honduras = Country 340

pattern Honduras :: Country
pattern Honduras = Country 340

-- | Hong Kong
hongKong :: Country
hongKong = Country 344

pattern HongKong :: Country
pattern HongKong = Country 344

-- | Hungary
hungary :: Country
hungary = Country 348

pattern Hungary :: Country
pattern Hungary = Country 348

-- | Iceland; Lýðveldið Ísland; Republic of Iceland; Ísafold; Ísland
iceland :: Country
iceland = Country 352

pattern Iceland :: Country
pattern Iceland = Country 352

-- | Al-Hind; Aryavarta; Bharatham; Bhārat; Bhārat Gaṇarājya; Bhārat Prajatantra; Bhāratadēśaṁ; Bhāratavarṣa; Hind; Hindustan; India; Republic of India; Union of India; ഇന്ത്യ
india :: Country
india = Country 356

pattern India :: Country
pattern India = Country 356

-- | Indonesia
indonesia :: Country
indonesia = Country 360

pattern Indonesia :: Country
pattern Indonesia = Country 360

-- | Faris; Iran; Iran (Islamic Republic of); Islamic Republic of Iran; Persia; The Islamic Republic of Iran
iranIslamicRepublicOf :: Country
iranIslamicRepublicOf = Country 364

pattern IranIslamicRepublicOf :: Country
pattern IranIslamicRepublicOf = Country 364

-- | Assyria; Babylon; Iraq; Mesopotamia
iraq :: Country
iraq = Country 368

pattern Iraq :: Country
pattern Iraq = Country 368

-- | Ireland; Irish Free State; Republic of Ireland; Saorstát Éireann; Éire
ireland :: Country
ireland = Country 372

pattern Ireland :: Country
pattern Ireland = Country 372

-- | Isle of Man
isleOfMan :: Country
isleOfMan = Country 833

pattern IsleOfMan :: Country
pattern IsleOfMan = Country 833

-- | Dawlat Isra'il; Hebrew State; Israel; Jewish State; Medinat Yisra'el; State of Israel; The Hebrew State; The Jewish State; מדינת ישראל; دَوْلَة إِسْرَائِيل
israel :: Country
israel = Country 376

pattern Israel :: Country
pattern Israel = Country 376

-- | Italy; Repubblica Italiana
italy :: Country
italy = Country 380

pattern Italy :: Country
pattern Italy = Country 380

-- | Jamaica; Xamayca
jamaica :: Country
jamaica = Country 388

pattern Jamaica :: Country
pattern Jamaica = Country 388

-- | Japan
japan :: Country
japan = Country 392

pattern Japan :: Country
pattern Japan = Country 392

-- | Jersey
jersey :: Country
jersey = Country 832

pattern Jersey :: Country
pattern Jersey = Country 832

-- | Hashemite Kingdom of Jordan; Jordan
jordan :: Country
jordan = Country 400

pattern Jordan :: Country
pattern Jordan = Country 400

-- | Kazakh Soviet Socialist Republic; Kazakhstan; Qazaq Keñestik Socïalïstik Respwblïkası; Qazaqstan; Republic of Kazakhstan; Қазақ Кеңестік Социалистік Республикасы; Қазақстан; Қазақстан Республикасы
kazakhstan :: Country
kazakhstan = Country 398

pattern Kazakhstan :: Country
pattern Kazakhstan = Country 398

-- | Jamhuri ya Kenya; Kenya; Republic of Kenya
kenya :: Country
kenya = Country 404

pattern Kenya :: Country
pattern Kenya = Country 404

-- | Kiribati
kiribati :: Country
kiribati = Country 296

pattern Kiribati :: Country
pattern Kiribati = Country 296

-- | Choson Minjujuui Inmin Konghwaguk; D.P.R.K.; DPRK; Democratic People's Republic of Korea; Korea (Democratic People's Republic of); North Korea; 조선민주주의인민공화국
koreaDemocraticPeoplesRepublicOf :: Country
koreaDemocraticPeoplesRepublicOf = Country 408

pattern KoreaDemocraticPeoplesRepublicOf :: Country
pattern KoreaDemocraticPeoplesRepublicOf = Country 408

-- | Korea (Republic of); Republic of Korea; South Korea
koreaRepublicOf :: Country
koreaRepublicOf = Country 410

pattern KoreaRepublicOf :: Country
pattern KoreaRepublicOf = Country 410

-- | Kuwait
kuwait :: Country
kuwait = Country 414

pattern Kuwait :: Country
pattern Kuwait = Country 414

-- | Kyrgyzstan
kyrgyzstan :: Country
kyrgyzstan = Country 417

pattern Kyrgyzstan :: Country
pattern Kyrgyzstan = Country 417

-- | Lao People's Democratic Republic; Laos
laoPeoplesDemocraticRepublic :: Country
laoPeoplesDemocraticRepublic = Country 418

pattern LaoPeoplesDemocraticRepublic :: Country
pattern LaoPeoplesDemocraticRepublic = Country 418

-- | Latvia; Latvija; Letland; Letonija; Letonnie; Lettland
latvia :: Country
latvia = Country 428

pattern Latvia :: Country
pattern Latvia = Country 428

-- | Lebanon
lebanon :: Country
lebanon = Country 422

pattern Lebanon :: Country
pattern Lebanon = Country 422

-- | Basutoland; Kingdom of Lesotho; Lesotho
lesotho :: Country
lesotho = Country 426

pattern Lesotho :: Country
pattern Lesotho = Country 426

-- | Liberia
liberia :: Country
liberia = Country 430

pattern Liberia :: Country
pattern Liberia = Country 430

-- | Libya
libya :: Country
libya = Country 434

pattern Libya :: Country
pattern Libya = Country 434

-- | Liechtenstein
liechtenstein :: Country
liechtenstein = Country 438

pattern Liechtenstein :: Country
pattern Liechtenstein = Country 438

-- | Lietuva; Lithuania; Lithuania, Republic of; Republic of Lithuania; Литва
lithuania :: Country
lithuania = Country 440

pattern Lithuania :: Country
pattern Lithuania = Country 440

-- | Grand Duchy of Luxembourg; Grand-Duché de Luxembourg; Groussherzogdem Lëtzebuerg; Großherzogtum Luxemburg; Lussemburgo; Luxembourg; Luxemburg; Luxemburgo
luxembourg :: Country
luxembourg = Country 442

pattern Luxembourg :: Country
pattern Luxembourg = Country 442

-- | Macao
macao :: Country
macao = Country 446

pattern Macao :: Country
pattern Macao = Country 446

-- | Macedonia; Macedonia (the former Yugoslav Republic of)
macedoniaTheFormerYugoslavRepublicOf :: Country
macedoniaTheFormerYugoslavRepublicOf = Country 807

pattern MacedoniaTheFormerYugoslavRepublicOf :: Country
pattern MacedoniaTheFormerYugoslavRepublicOf = Country 807

-- | Madagascar
madagascar :: Country
madagascar = Country 450

pattern Madagascar :: Country
pattern Madagascar = Country 450

-- | Malawi; Nyasaland; Republic of Malawi
malawi :: Country
malawi = Country 454

pattern Malawi :: Country
pattern Malawi = Country 454

-- | Federation of Malaysia; Malaysia; Mǎláixīyà; Persekutuan Malaysia; 马来西亚
malaysia :: Country
malaysia = Country 458

pattern Malaysia :: Country
pattern Malaysia = Country 458

-- | Dhibat-al-Mahal; Dhivehi Raajje; Mahal Dvipa; Maldives; Maléldvipa; Republic of the Maldives; The Maldive Islands; ދިވެހިރާއްޖެ
maldives :: Country
maldives = Country 462

pattern Maldives :: Country
pattern Maldives = Country 462

-- | Mali
mali :: Country
mali = Country 466

pattern Mali :: Country
pattern Mali = Country 466

-- | Malta
malta :: Country
malta = Country 470

pattern Malta :: Country
pattern Malta = Country 470

-- | Marshall Islands
marshallIslands :: Country
marshallIslands = Country 584

pattern MarshallIslands :: Country
pattern MarshallIslands = Country 584

-- | Martinique
martinique :: Country
martinique = Country 474

pattern Martinique :: Country
pattern Martinique = Country 474

-- | Islamic Republic of Mauritania; Mauritania; République Islamique de Mauritanie
mauritania :: Country
mauritania = Country 478

pattern Mauritania :: Country
pattern Mauritania = Country 478

-- | Mauritius
mauritius :: Country
mauritius = Country 480

pattern Mauritius :: Country
pattern Mauritius = Country 480

-- | Mayotte
mayotte :: Country
mayotte = Country 175

pattern Mayotte :: Country
pattern Mayotte = Country 175

-- | Aztlán; Aztlān; Estados Unidos Mexicanos; MX; Mejico; Mexico; Méjico; México; República Mexicana; United Mexican States
mexico :: Country
mexico = Country 484

pattern Mexico :: Country
pattern Mexico = Country 484

-- | Federated States of Micronesia; Micronesia; Micronesia (Federated States of)
micronesiaFederatedStatesOf :: Country
micronesiaFederatedStatesOf = Country 583

pattern MicronesiaFederatedStatesOf :: Country
pattern MicronesiaFederatedStatesOf = Country 583

-- | Moldova; Moldova (Republic of); Republic of Moldova
moldovaRepublicOf :: Country
moldovaRepublicOf = Country 498

pattern MoldovaRepublicOf :: Country
pattern MoldovaRepublicOf = Country 498

-- | Monaco; Principality of Monaco; Principauté de Monaco
monaco :: Country
monaco = Country 492

pattern Monaco :: Country
pattern Monaco = Country 492

-- | Mongolia
mongolia :: Country
mongolia = Country 496

pattern Mongolia :: Country
pattern Mongolia = Country 496

-- | Montenegro; Yugoslavia
montenegro :: Country
montenegro = Country 499

pattern Montenegro :: Country
pattern Montenegro = Country 499

-- | Montserrat
montserrat :: Country
montserrat = Country 500

pattern Montserrat :: Country
pattern Montserrat = Country 500

-- | Morocco
morocco :: Country
morocco = Country 504

pattern Morocco :: Country
pattern Morocco = Country 504

-- | Mozambique
mozambique :: Country
mozambique = Country 508

pattern Mozambique :: Country
pattern Mozambique = Country 508

-- | Burma; Myanmar; Myanmar (Burma); Myanmar [Burma]
myanmar :: Country
myanmar = Country 104

pattern Myanmar :: Country
pattern Myanmar = Country 104

-- | Namibia
namibia :: Country
namibia = Country 516

pattern Namibia :: Country
pattern Namibia = Country 516

-- | Nauru
nauru :: Country
nauru = Country 520

pattern Nauru :: Country
pattern Nauru = Country 520

-- | Nepal
nepal :: Country
nepal = Country 524

pattern Nepal :: Country
pattern Nepal = Country 524

-- | Netherlands
netherlands :: Country
netherlands = Country 528

pattern Netherlands :: Country
pattern Netherlands = Country 528

-- | New Caledonia
newCaledonia :: Country
newCaledonia = Country 540

pattern NewCaledonia :: Country
pattern NewCaledonia = Country 540

-- | New Zealand
newZealand :: Country
newZealand = Country 554

pattern NewZealand :: Country
pattern NewZealand = Country 554

-- | Nicaragua
nicaragua :: Country
nicaragua = Country 558

pattern Nicaragua :: Country
pattern Nicaragua = Country 558

-- | Niger
niger :: Country
niger = Country 562

pattern Niger :: Country
pattern Niger = Country 562

-- | Nigeria
nigeria :: Country
nigeria = Country 566

pattern Nigeria :: Country
pattern Nigeria = Country 566

-- | Niue
niue :: Country
niue = Country 570

pattern Niue :: Country
pattern Niue = Country 570

-- | Norfolk Island
norfolkIsland :: Country
norfolkIsland = Country 574

pattern NorfolkIsland :: Country
pattern NorfolkIsland = Country 574

-- | Northern Mariana Islands
northernMarianaIslands :: Country
northernMarianaIslands = Country 580

pattern NorthernMarianaIslands :: Country
pattern NorthernMarianaIslands = Country 580

-- | Norway
norway :: Country
norway = Country 578

pattern Norway :: Country
pattern Norway = Country 578

-- | Oman
oman :: Country
oman = Country 512

pattern Oman :: Country
pattern Oman = Country 512

-- | Pakistan
pakistan :: Country
pakistan = Country 586

pattern Pakistan :: Country
pattern Pakistan = Country 586

-- | Palau
palau :: Country
palau = Country 585

pattern Palau :: Country
pattern Palau = Country 585

-- | Palestine; Palestine, State of
palestineStateOf :: Country
palestineStateOf = Country 275

pattern PalestineStateOf :: Country
pattern PalestineStateOf = Country 275

-- | Panama
panama :: Country
panama = Country 591

pattern Panama :: Country
pattern Panama = Country 591

-- | Papua New Guinea
papuaNewGuinea :: Country
papuaNewGuinea = Country 598

pattern PapuaNewGuinea :: Country
pattern PapuaNewGuinea = Country 598

-- | Paraguay
paraguay :: Country
paraguay = Country 600

pattern Paraguay :: Country
pattern Paraguay = Country 600

-- | Peru
peru :: Country
peru = Country 604

pattern Peru :: Country
pattern Peru = Country 604

-- | Philippines
philippines :: Country
philippines = Country 608

pattern Philippines :: Country
pattern Philippines = Country 608

-- | Pitcairn; Pitcairn Islands
pitcairn :: Country
pitcairn = Country 612

pattern Pitcairn :: Country
pattern Pitcairn = Country 612

-- | Poland
poland :: Country
poland = Country 616

pattern Poland :: Country
pattern Poland = Country 616

-- | Portugal
portugal :: Country
portugal = Country 620

pattern Portugal :: Country
pattern Portugal = Country 620

-- | Puerto Rico
puertoRico :: Country
puertoRico = Country 630

pattern PuertoRico :: Country
pattern PuertoRico = Country 630

-- | Qatar
qatar :: Country
qatar = Country 634

pattern Qatar :: Country
pattern Qatar = Country 634

-- | Réunion
réunion :: Country
réunion = Country 638

pattern Réunion :: Country
pattern Réunion = Country 638

-- | Kingdom of Romania; Regatul României; Republica Populară Romînă; Republica Socialistă România; Romania; Romanian People's Republic; România; Roumania; Rumania; Socialist Republic of Romania
romania :: Country
romania = Country 642

pattern Romania :: Country
pattern Romania = Country 642

-- | Great Russia; R.F.; RF; RSFSR; Rossiya; Rus; Russia; Russian Federation; Russian Socialist Federative Soviet Republic; Russian Soviet Federative Socialist Republic; Russland; SSSR; SU; Sovetskiy Soyuz; Soviet Union; Soyuz Sovetskikh Sotsialisticheskikh Respublik; USSR; Union of Soviet Socialist Republics; Российская Федерация; Россия; СССР; Сове́тский Сою́з; Союз Советских Социалистических Республик
russianFederation :: Country
russianFederation = Country 643

pattern RussianFederation :: Country
pattern RussianFederation = Country 643

-- | Republic of Rwanda; Repubulika y'u Rwanda; Ruanda; Rwanda; Rwandese Republic; République du Rwanda
rwanda :: Country
rwanda = Country 646

pattern Rwanda :: Country
pattern Rwanda = Country 646

-- | Saint Barthélemy; Saint-Barthélemy
saintBarthélemy :: Country
saintBarthélemy = Country 652

pattern SaintBarthélemy :: Country
pattern SaintBarthélemy = Country 652

-- | Saint Helena; Saint Helena, Ascension and Tristan da Cunha
saintHelenaAscensionAndTristanDaCunha :: Country
saintHelenaAscensionAndTristanDaCunha = Country 654

pattern SaintHelenaAscensionAndTristanDaCunha :: Country
pattern SaintHelenaAscensionAndTristanDaCunha = Country 654

-- | Federation of Saint Kitts and Nevis; Saint Kitts and Nevis; Saint Kitts-Nevis-Anguilla; St Kitts and Nevis; St. Kitts and Nevis
saintKittsAndNevis :: Country
saintKittsAndNevis = Country 659

pattern SaintKittsAndNevis :: Country
pattern SaintKittsAndNevis = Country 659

-- | Saint Lucia
saintLucia :: Country
saintLucia = Country 662

pattern SaintLucia :: Country
pattern SaintLucia = Country 662

-- | Saint Martin; Saint Martin (French part); St Martin; St. Martin
saintMartinFrenchPart :: Country
saintMartinFrenchPart = Country 663

pattern SaintMartinFrenchPart :: Country
pattern SaintMartinFrenchPart = Country 663

-- | Saint Pierre and Miquelon
saintPierreAndMiquelon :: Country
saintPierreAndMiquelon = Country 666

pattern SaintPierreAndMiquelon :: Country
pattern SaintPierreAndMiquelon = Country 666

-- | Saint Vincent and the Grenadines; St Vincent and Grenadines
saintVincentAndTheGrenadines :: Country
saintVincentAndTheGrenadines = Country 670

pattern SaintVincentAndTheGrenadines :: Country
pattern SaintVincentAndTheGrenadines = Country 670

-- | Samoa
samoa :: Country
samoa = Country 882

pattern Samoa :: Country
pattern Samoa = Country 882

-- | San Marino
sanMarino :: Country
sanMarino = Country 674

pattern SanMarino :: Country
pattern SanMarino = Country 674

-- | Sao Tome and Principe; São Tomé and Príncipe
saoTomeAndPrincipe :: Country
saoTomeAndPrincipe = Country 678

pattern SaoTomeAndPrincipe :: Country
pattern SaoTomeAndPrincipe = Country 678

-- | Saudi Arabia
saudiArabia :: Country
saudiArabia = Country 682

pattern SaudiArabia :: Country
pattern SaudiArabia = Country 682

-- | Senegal
senegal :: Country
senegal = Country 686

pattern Senegal :: Country
pattern Senegal = Country 686

-- | Serbia
serbia :: Country
serbia = Country 688

pattern Serbia :: Country
pattern Serbia = Country 688

-- | Seychelles
seychelles :: Country
seychelles = Country 690

pattern Seychelles :: Country
pattern Seychelles = Country 690

-- | Sierra Leone
sierraLeone :: Country
sierraLeone = Country 694

pattern SierraLeone :: Country
pattern SierraLeone = Country 694

-- | Republic of Singapore; Singapore; Singapura
singapore :: Country
singapore = Country 702

pattern Singapore :: Country
pattern Singapore = Country 702

-- | Sint Maarten; Sint Maarten (Dutch part)
sintMaartenDutchPart :: Country
sintMaartenDutchPart = Country 534

pattern SintMaartenDutchPart :: Country
pattern SintMaartenDutchPart = Country 534

-- | Slovakia
slovakia :: Country
slovakia = Country 703

pattern Slovakia :: Country
pattern Slovakia = Country 703

-- | Slovenia
slovenia :: Country
slovenia = Country 705

pattern Slovenia :: Country
pattern Slovenia = Country 705

-- | Solomon Islands
solomonIslands :: Country
solomonIslands = Country 90

pattern SolomonIslands :: Country
pattern SolomonIslands = Country 90

-- | Somalia
somalia :: Country
somalia = Country 706

pattern Somalia :: Country
pattern Somalia = Country 706

-- | South Africa
southAfrica :: Country
southAfrica = Country 710

pattern SouthAfrica :: Country
pattern SouthAfrica = Country 710

-- | South Georgia and the South Sandwich Islands
southGeorgiaAndTheSouthSandwichIslands :: Country
southGeorgiaAndTheSouthSandwichIslands = Country 239

pattern SouthGeorgiaAndTheSouthSandwichIslands :: Country
pattern SouthGeorgiaAndTheSouthSandwichIslands = Country 239

-- | Republic of South Sudan; South Sudan
southSudan :: Country
southSudan = Country 728

pattern SouthSudan :: Country
pattern SouthSudan = Country 728

-- | Espainia; Espanya; España; Hispania; Iberia; Reino de España; Spain; Spanish State
spain :: Country
spain = Country 724

pattern Spain :: Country
pattern Spain = Country 724

-- | Sri Lanka
sriLanka :: Country
sriLanka = Country 144

pattern SriLanka :: Country
pattern SriLanka = Country 144

-- | Nubia; Republic of the Sudan; Sudan; The Sudan
sudan :: Country
sudan = Country 729

pattern Sudan :: Country
pattern Sudan = Country 729

-- | Dutch Guiana; Netherlands Guiana; Republic of Suriname; Republiek Suriname; Surinam; Suriname
suriname :: Country
suriname = Country 740

pattern Suriname :: Country
pattern Suriname = Country 740

-- | Svalbard and Jan Mayen
svalbardAndJanMayen :: Country
svalbardAndJanMayen = Country 744

pattern SvalbardAndJanMayen :: Country
pattern SvalbardAndJanMayen = Country 744

-- | Swaziland
swaziland :: Country
swaziland = Country 748

pattern Swaziland :: Country
pattern Swaziland = Country 748

-- | Kingdom of Sweden; Konungariket Sverige; Svea Rike; Sverige; Svitjod; Sweden
sweden :: Country
sweden = Country 752

pattern Sweden :: Country
pattern Sweden = Country 752

-- | CH; Confederazione Svizzera; Confederaziun Svizra; Confoederatio Helvetica; Confédération suisse; Helvetia; Schweiz; Schweizerische Eidgenossenschaft; Suisse; Svizra; Svizzera; Swiss Confederation; Switzerland
switzerland :: Country
switzerland = Country 756

pattern Switzerland :: Country
pattern Switzerland = Country 756

-- | Syria; Syrian Arab Republic
syrianArabRepublic :: Country
syrianArabRepublic = Country 760

pattern SyrianArabRepublic :: Country
pattern SyrianArabRepublic = Country 760

-- | Chinese Taipei; People's Republic of China; Republic of China; Separate Customs Territory of Taiwan, Penghu, Kinmen and Matsu; Taiwan; Taiwan, Province of China; The People's Republic of China; Zhonggua Taipei; 中華台北
taiwanProvinceOfChina :: Country
taiwanProvinceOfChina = Country 158

pattern TaiwanProvinceOfChina :: Country
pattern TaiwanProvinceOfChina = Country 158

-- | Tajikistan
tajikistan :: Country
tajikistan = Country 762

pattern Tajikistan :: Country
pattern Tajikistan = Country 762

-- | Tanzania; Tanzania, United Republic of; United Republic of Tanganyika and Zanzibar
tanzaniaUnitedRepublicOf :: Country
tanzaniaUnitedRepublicOf = Country 834

pattern TanzaniaUnitedRepublicOf :: Country
pattern TanzaniaUnitedRepublicOf = Country 834

-- | Thailand
thailand :: Country
thailand = Country 764

pattern Thailand :: Country
pattern Thailand = Country 764

-- | Democratic Republic of Timor-Leste; Timor-Leste
timorleste :: Country
timorleste = Country 626

pattern Timorleste :: Country
pattern Timorleste = Country 626

-- | Togo
togo :: Country
togo = Country 768

pattern Togo :: Country
pattern Togo = Country 768

-- | Tokelau
tokelau :: Country
tokelau = Country 772

pattern Tokelau :: Country
pattern Tokelau = Country 772

-- | Tonga
tonga :: Country
tonga = Country 776

pattern Tonga :: Country
pattern Tonga = Country 776

-- | Republic of Trinidad and Tobago; Trinbago; Trinidad and Tobago
trinidadAndTobago :: Country
trinidadAndTobago = Country 780

pattern TrinidadAndTobago :: Country
pattern TrinidadAndTobago = Country 780

-- | Tunisia
tunisia :: Country
tunisia = Country 788

pattern Tunisia :: Country
pattern Tunisia = Country 788

-- | Ottoman Empire; Republic of Turkey; Turkey; Turkish Empire; Türkiye Cumhuriyeti
turkey :: Country
turkey = Country 792

pattern Turkey :: Country
pattern Turkey = Country 792

-- | Turkmenistan
turkmenistan :: Country
turkmenistan = Country 795

pattern Turkmenistan :: Country
pattern Turkmenistan = Country 795

-- | Turks and Caicos Islands
turksAndCaicosIslands :: Country
turksAndCaicosIslands = Country 796

pattern TurksAndCaicosIslands :: Country
pattern TurksAndCaicosIslands = Country 796

-- | Tuvalu
tuvalu :: Country
tuvalu = Country 798

pattern Tuvalu :: Country
pattern Tuvalu = Country 798

-- | Uganda
uganda :: Country
uganda = Country 800

pattern Uganda :: Country
pattern Uganda = Country 800

-- | UA; UKR; Ukraine; Ukraїna
ukraine :: Country
ukraine = Country 804

pattern Ukraine :: Country
pattern Ukraine = Country 804

-- | Al Emirat al Arabbiya al Muttahida; U.A.E.; UAE; United Arab Emirates
unitedArabEmirates :: Country
unitedArabEmirates = Country 784

pattern UnitedArabEmirates :: Country
pattern UnitedArabEmirates = Country 784

-- | United Kingdom; United Kingdom of Great Britain and Northern Ireland
unitedKingdomOfGreatBritainAndNorthernIreland :: Country
unitedKingdomOfGreatBritainAndNorthernIreland = Country 826

pattern UnitedKingdomOfGreatBritainAndNorthernIreland :: Country
pattern UnitedKingdomOfGreatBritainAndNorthernIreland = Country 826

-- | Estados Unidos de América; The United States; U.S.; U.S.A.; USA; United States; United States of America; Usa; Usono
unitedStatesOfAmerica :: Country
unitedStatesOfAmerica = Country 840

pattern UnitedStatesOfAmerica :: Country
pattern UnitedStatesOfAmerica = Country 840

-- | U.S. Minor Outlying Islands; U.S. Outlying Islands; United States Minor Outlying Islands
unitedStatesMinorOutlyingIslands :: Country
unitedStatesMinorOutlyingIslands = Country 581

pattern UnitedStatesMinorOutlyingIslands :: Country
pattern UnitedStatesMinorOutlyingIslands = Country 581

-- | Uruguay
uruguay :: Country
uruguay = Country 858

pattern Uruguay :: Country
pattern Uruguay = Country 858

-- | Uzbekistan
uzbekistan :: Country
uzbekistan = Country 860

pattern Uzbekistan :: Country
pattern Uzbekistan = Country 860

-- | Ripablik blong Vanuatu; République de Vanuatu; Vanuatu
vanuatu :: Country
vanuatu = Country 548

pattern Vanuatu :: Country
pattern Vanuatu = Country 548

-- | Bolivarian Republic of Venezuela; República Bolivariana de Venezuela; Venezuela; Venezuela (Bolivarian Republic of)
venezuelaBolivarianRepublicOf :: Country
venezuelaBolivarianRepublicOf = Country 862

pattern VenezuelaBolivarianRepublicOf :: Country
pattern VenezuelaBolivarianRepublicOf = Country 862

-- | Cộng hòa Xã hội Chủ nghĩa Việt Nam; Viet Nam; Vietnam; Việt Nam
vietNam :: Country
vietNam = Country 704

pattern VietNam :: Country
pattern VietNam = Country 704

-- | British Virgin Islands; Virgin Islands (British)
virginIslandsBritish :: Country
virginIslandsBritish = Country 92

pattern VirginIslandsBritish :: Country
pattern VirginIslandsBritish = Country 92

-- | U.S. Virgin Islands; Virgin Islands (U.S.)
virginIslandsUs :: Country
virginIslandsUs = Country 850

pattern VirginIslandsUs :: Country
pattern VirginIslandsUs = Country 850

-- | Wallis and Futuna
wallisAndFutuna :: Country
wallisAndFutuna = Country 876

pattern WallisAndFutuna :: Country
pattern WallisAndFutuna = Country 876

-- | Western Sahara
westernSahara :: Country
westernSahara = Country 732

pattern WesternSahara :: Country
pattern WesternSahara = Country 732

-- | Yemen
yemen :: Country
yemen = Country 887

pattern Yemen :: Country
pattern Yemen = Country 887

-- | Republic of Zambia; Zambia
zambia :: Country
zambia = Country 894

pattern Zambia :: Country
pattern Zambia = Country 894

-- | Republic of Zimbabwe; Zimbabwe
zimbabwe :: Country
zimbabwe = Country 716

pattern Zimbabwe :: Country
pattern Zimbabwe = Country 716

-- | Kosovo
kosovo :: Country
kosovo = Country 383

pattern Kosovo :: Country
pattern Kosovo = Country 383

