module Country.Identifier where

-- This module is autogenerated. Do not edit it by hand.

import Country.Unsafe (Country(..))

afghanistan :: Country
afghanistan = Country 4

ålandIslands :: Country
ålandIslands = Country 248

albania :: Country
albania = Country 8

algeria :: Country
algeria = Country 12

americanSamoa :: Country
americanSamoa = Country 16

andorra :: Country
andorra = Country 20

angola :: Country
angola = Country 24

anguilla :: Country
anguilla = Country 660

antarctica :: Country
antarctica = Country 10

antiguaAndBarbuda :: Country
antiguaAndBarbuda = Country 28

argentina :: Country
argentina = Country 32

armenia :: Country
armenia = Country 51

aruba :: Country
aruba = Country 533

australia :: Country
australia = Country 36

austria :: Country
austria = Country 40

azerbaijan :: Country
azerbaijan = Country 31

bahamas :: Country
bahamas = Country 44

bahrain :: Country
bahrain = Country 48

bangladesh :: Country
bangladesh = Country 50

barbados :: Country
barbados = Country 52

belarus :: Country
belarus = Country 112

belgium :: Country
belgium = Country 56

belize :: Country
belize = Country 84

benin :: Country
benin = Country 204

bermuda :: Country
bermuda = Country 60

bhutan :: Country
bhutan = Country 64

boliviaPlurinationalStateOf :: Country
boliviaPlurinationalStateOf = Country 68

bonaireSintEustatiusAndSaba :: Country
bonaireSintEustatiusAndSaba = Country 535

bosniaAndHerzegovina :: Country
bosniaAndHerzegovina = Country 70

botswana :: Country
botswana = Country 72

bouvetIsland :: Country
bouvetIsland = Country 74

brazil :: Country
brazil = Country 76

britishIndianOceanTerritory :: Country
britishIndianOceanTerritory = Country 86

bruneiDarussalam :: Country
bruneiDarussalam = Country 96

bulgaria :: Country
bulgaria = Country 100

burkinaFaso :: Country
burkinaFaso = Country 854

burundi :: Country
burundi = Country 108

cambodia :: Country
cambodia = Country 116

cameroon :: Country
cameroon = Country 120

canada :: Country
canada = Country 124

caboVerde :: Country
caboVerde = Country 132

caymanIslands :: Country
caymanIslands = Country 136

centralAfricanRepublic :: Country
centralAfricanRepublic = Country 140

chad :: Country
chad = Country 148

chile :: Country
chile = Country 152

china :: Country
china = Country 156

christmasIsland :: Country
christmasIsland = Country 162

cocosKeelingIslands :: Country
cocosKeelingIslands = Country 166

colombia :: Country
colombia = Country 170

comoros :: Country
comoros = Country 174

congo :: Country
congo = Country 178

congoDemocraticRepublicOfThe :: Country
congoDemocraticRepublicOfThe = Country 180

cookIslands :: Country
cookIslands = Country 184

costaRica :: Country
costaRica = Country 188

côteDivoire :: Country
côteDivoire = Country 384

croatia :: Country
croatia = Country 191

cuba :: Country
cuba = Country 192

curaçao :: Country
curaçao = Country 531

cyprus :: Country
cyprus = Country 196

czechRepublic :: Country
czechRepublic = Country 203

denmark :: Country
denmark = Country 208

djibouti :: Country
djibouti = Country 262

dominica :: Country
dominica = Country 212

dominicanRepublic :: Country
dominicanRepublic = Country 214

ecuador :: Country
ecuador = Country 218

egypt :: Country
egypt = Country 818

elSalvador :: Country
elSalvador = Country 222

equatorialGuinea :: Country
equatorialGuinea = Country 226

eritrea :: Country
eritrea = Country 232

estonia :: Country
estonia = Country 233

ethiopia :: Country
ethiopia = Country 231

falklandIslandsMalvinas :: Country
falklandIslandsMalvinas = Country 238

faroeIslands :: Country
faroeIslands = Country 234

fiji :: Country
fiji = Country 242

finland :: Country
finland = Country 246

france :: Country
france = Country 250

frenchGuiana :: Country
frenchGuiana = Country 254

frenchPolynesia :: Country
frenchPolynesia = Country 258

frenchSouthernTerritories :: Country
frenchSouthernTerritories = Country 260

gabon :: Country
gabon = Country 266

gambia :: Country
gambia = Country 270

georgia :: Country
georgia = Country 268

germany :: Country
germany = Country 276

ghana :: Country
ghana = Country 288

gibraltar :: Country
gibraltar = Country 292

greece :: Country
greece = Country 300

greenland :: Country
greenland = Country 304

grenada :: Country
grenada = Country 308

guadeloupe :: Country
guadeloupe = Country 312

guam :: Country
guam = Country 316

guatemala :: Country
guatemala = Country 320

guernsey :: Country
guernsey = Country 831

guinea :: Country
guinea = Country 324

guineabissau :: Country
guineabissau = Country 624

guyana :: Country
guyana = Country 328

haiti :: Country
haiti = Country 332

heardIslandAndMcdonaldIslands :: Country
heardIslandAndMcdonaldIslands = Country 334

holySee :: Country
holySee = Country 336

honduras :: Country
honduras = Country 340

hongKong :: Country
hongKong = Country 344

hungary :: Country
hungary = Country 348

iceland :: Country
iceland = Country 352

india :: Country
india = Country 356

indonesia :: Country
indonesia = Country 360

iranIslamicRepublicOf :: Country
iranIslamicRepublicOf = Country 364

iraq :: Country
iraq = Country 368

ireland :: Country
ireland = Country 372

isleOfMan :: Country
isleOfMan = Country 833

israel :: Country
israel = Country 376

italy :: Country
italy = Country 380

jamaica :: Country
jamaica = Country 388

japan :: Country
japan = Country 392

jersey :: Country
jersey = Country 832

jordan :: Country
jordan = Country 400

kazakhstan :: Country
kazakhstan = Country 398

kenya :: Country
kenya = Country 404

kiribati :: Country
kiribati = Country 296

koreaDemocraticPeoplesRepublicOf :: Country
koreaDemocraticPeoplesRepublicOf = Country 408

koreaRepublicOf :: Country
koreaRepublicOf = Country 410

kuwait :: Country
kuwait = Country 414

kyrgyzstan :: Country
kyrgyzstan = Country 417

laoPeoplesDemocraticRepublic :: Country
laoPeoplesDemocraticRepublic = Country 418

latvia :: Country
latvia = Country 428

lebanon :: Country
lebanon = Country 422

lesotho :: Country
lesotho = Country 426

liberia :: Country
liberia = Country 430

libya :: Country
libya = Country 434

liechtenstein :: Country
liechtenstein = Country 438

lithuania :: Country
lithuania = Country 440

luxembourg :: Country
luxembourg = Country 442

macao :: Country
macao = Country 446

macedoniaTheFormerYugoslavRepublicOf :: Country
macedoniaTheFormerYugoslavRepublicOf = Country 807

madagascar :: Country
madagascar = Country 450

malawi :: Country
malawi = Country 454

malaysia :: Country
malaysia = Country 458

maldives :: Country
maldives = Country 462

mali :: Country
mali = Country 466

malta :: Country
malta = Country 470

marshallIslands :: Country
marshallIslands = Country 584

martinique :: Country
martinique = Country 474

mauritania :: Country
mauritania = Country 478

mauritius :: Country
mauritius = Country 480

mayotte :: Country
mayotte = Country 175

mexico :: Country
mexico = Country 484

micronesiaFederatedStatesOf :: Country
micronesiaFederatedStatesOf = Country 583

moldovaRepublicOf :: Country
moldovaRepublicOf = Country 498

monaco :: Country
monaco = Country 492

mongolia :: Country
mongolia = Country 496

montenegro :: Country
montenegro = Country 499

montserrat :: Country
montserrat = Country 500

morocco :: Country
morocco = Country 504

mozambique :: Country
mozambique = Country 508

myanmar :: Country
myanmar = Country 104

namibia :: Country
namibia = Country 516

nauru :: Country
nauru = Country 520

nepal :: Country
nepal = Country 524

netherlands :: Country
netherlands = Country 528

newCaledonia :: Country
newCaledonia = Country 540

newZealand :: Country
newZealand = Country 554

nicaragua :: Country
nicaragua = Country 558

niger :: Country
niger = Country 562

nigeria :: Country
nigeria = Country 566

niue :: Country
niue = Country 570

norfolkIsland :: Country
norfolkIsland = Country 574

northernMarianaIslands :: Country
northernMarianaIslands = Country 580

norway :: Country
norway = Country 578

oman :: Country
oman = Country 512

pakistan :: Country
pakistan = Country 586

palau :: Country
palau = Country 585

palestineStateOf :: Country
palestineStateOf = Country 275

panama :: Country
panama = Country 591

papuaNewGuinea :: Country
papuaNewGuinea = Country 598

paraguay :: Country
paraguay = Country 600

peru :: Country
peru = Country 604

philippines :: Country
philippines = Country 608

pitcairn :: Country
pitcairn = Country 612

poland :: Country
poland = Country 616

portugal :: Country
portugal = Country 620

puertoRico :: Country
puertoRico = Country 630

qatar :: Country
qatar = Country 634

réunion :: Country
réunion = Country 638

romania :: Country
romania = Country 642

russianFederation :: Country
russianFederation = Country 643

rwanda :: Country
rwanda = Country 646

saintBarthélemy :: Country
saintBarthélemy = Country 652

saintHelenaAscensionAndTristanDaCunha :: Country
saintHelenaAscensionAndTristanDaCunha = Country 654

saintKittsAndNevis :: Country
saintKittsAndNevis = Country 659

saintLucia :: Country
saintLucia = Country 662

saintMartinFrenchPart :: Country
saintMartinFrenchPart = Country 663

saintPierreAndMiquelon :: Country
saintPierreAndMiquelon = Country 666

saintVincentAndTheGrenadines :: Country
saintVincentAndTheGrenadines = Country 670

samoa :: Country
samoa = Country 882

sanMarino :: Country
sanMarino = Country 674

saoTomeAndPrincipe :: Country
saoTomeAndPrincipe = Country 678

saudiArabia :: Country
saudiArabia = Country 682

senegal :: Country
senegal = Country 686

serbia :: Country
serbia = Country 688

seychelles :: Country
seychelles = Country 690

sierraLeone :: Country
sierraLeone = Country 694

singapore :: Country
singapore = Country 702

sintMaartenDutchPart :: Country
sintMaartenDutchPart = Country 534

slovakia :: Country
slovakia = Country 703

slovenia :: Country
slovenia = Country 705

solomonIslands :: Country
solomonIslands = Country 90

somalia :: Country
somalia = Country 706

southAfrica :: Country
southAfrica = Country 710

southGeorgiaAndTheSouthSandwichIslands :: Country
southGeorgiaAndTheSouthSandwichIslands = Country 239

southSudan :: Country
southSudan = Country 728

spain :: Country
spain = Country 724

sriLanka :: Country
sriLanka = Country 144

sudan :: Country
sudan = Country 729

suriname :: Country
suriname = Country 740

svalbardAndJanMayen :: Country
svalbardAndJanMayen = Country 744

swaziland :: Country
swaziland = Country 748

sweden :: Country
sweden = Country 752

switzerland :: Country
switzerland = Country 756

syrianArabRepublic :: Country
syrianArabRepublic = Country 760

taiwanProvinceOfChina :: Country
taiwanProvinceOfChina = Country 158

tajikistan :: Country
tajikistan = Country 762

tanzaniaUnitedRepublicOf :: Country
tanzaniaUnitedRepublicOf = Country 834

thailand :: Country
thailand = Country 764

timorleste :: Country
timorleste = Country 626

togo :: Country
togo = Country 768

tokelau :: Country
tokelau = Country 772

tonga :: Country
tonga = Country 776

trinidadAndTobago :: Country
trinidadAndTobago = Country 780

tunisia :: Country
tunisia = Country 788

turkey :: Country
turkey = Country 792

turkmenistan :: Country
turkmenistan = Country 795

turksAndCaicosIslands :: Country
turksAndCaicosIslands = Country 796

tuvalu :: Country
tuvalu = Country 798

uganda :: Country
uganda = Country 800

ukraine :: Country
ukraine = Country 804

unitedArabEmirates :: Country
unitedArabEmirates = Country 784

unitedKingdomOfGreatBritainAndNorthernIreland :: Country
unitedKingdomOfGreatBritainAndNorthernIreland = Country 826

unitedStatesOfAmerica :: Country
unitedStatesOfAmerica = Country 840

unitedStatesMinorOutlyingIslands :: Country
unitedStatesMinorOutlyingIslands = Country 581

uruguay :: Country
uruguay = Country 858

uzbekistan :: Country
uzbekistan = Country 860

vanuatu :: Country
vanuatu = Country 548

venezuelaBolivarianRepublicOf :: Country
venezuelaBolivarianRepublicOf = Country 862

vietNam :: Country
vietNam = Country 704

virginIslandsBritish :: Country
virginIslandsBritish = Country 92

virginIslandsUs :: Country
virginIslandsUs = Country 850

wallisAndFutuna :: Country
wallisAndFutuna = Country 876

westernSahara :: Country
westernSahara = Country 732

yemen :: Country
yemen = Country 887

zambia :: Country
zambia = Country 894

zimbabwe :: Country
zimbabwe = Country 716

kosovo :: Country
kosovo = Country 383

